version: '3.7'

services:

  auth:
    build:
      context: ./services/auth/
    entrypoint: ./run.sh
    restart: unless-stopped
    depends_on:
      - auth_db
      - kafka
    ports:
      - 9229:9229
    volumes:
      - ./services/auth:/app
      - ./services/schema-registry:/schema-registry
      - /app/node_modules
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
      - KAFKA_BROKERS
      - JWT_SECRET
      - AUTH_SALT
      - AUTH_DB
      - AUTH_DB_USER
      - AUTH_DB_PASSWORD
    networks:
      - ates-network

  auth_db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${AUTH_DB}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    ports:
      - 5432:5432
    command: postgres -c log_statement=all -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    networks:
      - ates-network
